export const objNewTestament = [
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 1,
    verse: "После того, как Йешуа родился в Бейт-Лехеме в земле Й'гуды во время царствования Ирода, в Йерушалаим пришли Маги с востока",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 2,
    verse: "и спрашивали: 'Где новорождённый Царь евреев? Ибо мы увидели его звезду на востоке и пришли поклониться ему'.",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 3,
    verse: "Когда это услышал царь Ирод, он встревожился, а с ним и все остальные жители Йерушалаима",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 4,
    verse: "Созвав всех руководящих в народе коганим и учителей Торы, он спросил их: 'Где родится Мессия?'",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 5,
    verse: "",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 6,
    verse: "И ты, Бейт-Лехем в земле Й'гуды, отнюдь не меньший среди правителей Й'гуды; Ибо из тебя произойдёт Владыка, который будет пасти народ мой Израиль",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 7,
    verse: "",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 8,
    verse: "",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 9,
    verse: "",
    comment: '',
  },
  {
    name: 'Матфей',
    chapter: '',
    id_nz: 1,
    id_chapter: 2,
    id: 10,
    verse: "",
    comment: '',
  },
]